story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_6.urls')),
    path('activity/', include('story_6.urls')),
    path('story7/', include('story_7.urls')),
    path('story8/', include('story_8.urls')),
]

story_6/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.activity, name='activity'),
    path('add/', views.add_activity, name='add_activity'),
    path('register/<int:index>/', views.register, name='register'),
]

story_7/urls.py
from django.urls import path
from . import views

app_name = 'story_7'

urlpatterns = [
    path('', views.story7, name='story7'),
]

story_8/urls.py
from django.urls import path
from . import views

app_name = 'story_8'

urlpatterns = [
    path('', views.story8, name='story8'),
]

story_6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
	kegiatan = models.CharField('Activity Name', max_length=120)
	
class Person(models.Model):
	kegiatan = models.ForeignKey('Activity', on_delete=models.CASCADE, null=True, blank=True)
	nama = models.CharField('Name', max_length=120)

story_7/models.py
from django.db import models

# Create your models here.

story_8/models.py
from django.db import models

# Create your models here.

story_6/forms.py
from django.forms import ModelForm
from .models import Activity, Person

class ActivityForm(ModelForm):
	required_css_class = 'required'
	class Meta:
		model = Activity
		fields = '__all__'

class PersonForm(ModelForm):
	class Meta:
		model = Person
		fields = ['nama']

story_6/views.py
from django.shortcuts import render, redirect
from .models import Activity, Person
from .forms import ActivityForm, PersonForm

# Create your views here.
def activity(request):
	activity = Activity.objects.all()
	attendees = Person.objects.all()

	if request.method == "POST":
		Person.objects.get(id=request.POST['id']).delete()
		return redirect('/activity/')

	return render(request, 'activity.html', {'activity': activity, 'attendees': attendees})

def add_activity(request):
	if request.method == 'POST':
		form = ActivityForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/activity/')
	else:
		form = ActivityForm()
	return render(request, 'add_activity.html', {'form': form})

def register(request, index):
	if request.method == 'POST':
		form = PersonForm(request.POST)
		if form.is_valid():
			newPerson = Person(kegiatan=Activity.objects.get(id=index), nama=form.data['nama'])
			newPerson.save()
			return redirect('/activity/')
	else:
		form = PersonForm()
	return render(request, 'register.html', {'form': form})

story_7/views.py
from django.shortcuts import render

# Create your views here.
def story7(request):
	return render(request, 'story7.html')

story_8/views.py
from django.shortcuts import render

# Create your views here.
def story8(request):
	return render(request, 'story8.html')

def data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    return JsonResponse(ret.json(), safe=False)

story_6/templates/activity.html
{% extends 'base_story6.html' %}
{% load static %}
{% block title %} Activity {% endblock %}

{% block content %}

<section class="container-fluid d-flex flex-wrap align-content-center mt-5">
	<div class="section-title mx-auto text-center mt-5"> 
			ACTIVITY LIST
	  <a href="{% url 'story_6:add_activity' %}" class="text-white">
		<button class="btn btn-primary d-flex mx-auto my-2 click">
			Add New Activity
		</button>
	  </a>
	</div>

	<div class="row w-100 justify-content-center">
		{% for x in activity %}
			<div class="col-4 m-4 p-4 rounded border">
				<ul class="list-group">
				  <li class="list-group-item list-group-item-secondary"> <b> {{ x.kegiatan }} </b> </li>

			      {% for y in attendees %}
				    {% if y.kegiatan == x %}
					  	<form method="POST" action="{% url 'story_6:activity' %}">
					    {% csrf_token %}
					    <input name="id" value="{{y.id}}" type="hidden">
				  		<li class="list-group-item"> 
				  			<div class="d-flex justify-content-between"> 
				  				{{ y.nama }} 
					          <button type="submit" value="Submit" class="btn btn-primary" style="font-size: 0.8rem;"> 
					          x
					           </button>
					        </form>
				  			</div>
				  		</li>
				    {% endif %}
			      {% endfor %}
				</ul>

				<div class="section-title mx-auto text-center"> 
				  <a href="register/{{ x.id }}" class="text-white">
					<button class="btn btn-primary d-flex mx-auto my-2 click">
					  	Register Yourself
					</button>
				  </a>
				</div>
			</div>
		{% endfor %}
	</div>

</section>
{% endblock %}

story_6/templates/add_activity.html
{% extends "base_story6.html" %}
{% load static %}
{% block title %}Add Activity{% endblock %}
{% block content %}



<section class="container-fluid d-flex flex-wrap align-content-center ">
	<div class="section-title mx-auto text-center p-5"> 
		ADD NEW ACTIVITY
	</div>

	<form action="" method="post" novalidate>
		{% csrf_token %}
		<table class="table mx-5" style="width:90vw">
			{{ form.as_table }}
			<tr>
				<td>&nbsp;</td>
				<td><input type="submit" value="Submit" class="btn btn-primary click"></td>
			</tr>
		</table>
	</form>

</section>

{% endblock content %}

story_6/templates/base_story6.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
    {% block content %}
    {% endblock %}
    </body>
</html>

story_6/templates/register.html
{% extends "base_story6.html" %}
{% load static %}
{% block title %}Regist Yourself{% endblock %}
{% block content %}



<section class="container-fluid d-flex flex-wrap align-content-center ">
	<div class="section-title mx-auto text-center p-5"> 
		REGIST YOURSELF
	</div>

	<form action="" method="post" novalidate>
		{% csrf_token %}
		<table class="table mx-5" style="width:90vw">
			{{ form.as_table }}
			<tr>
				<td>&nbsp;</td>
				<td><input type="submit" value="Submit" class="btn btn-primary click"></td>
			</tr>
		</table>
	</form>

</section>

{% endblock content %}

story_7/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/new-style.css' %}">
        {% block style %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
        {% block script %}{% endblock %}
    </body>
</html>

story_7/templates/story7.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 7 {% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/new-style.css' %}">
<section class="normal">
  <div class="section-title"> ACCORDION </div>

  <div class="accordion-container">
    <div id="number1" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Number 1 
        <div>
          <button class="up"> /\ </button>
          <button class="down"> \/ </button>
        </div>
      </a>

      <div class="content">
        <p> Hello </p>
      </div>
    </div>

    <div id="number2" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Number 2
        <div>
          <button class="up"> /\ </button>
          <button class="down"> \/ </button>
        </div>
      </a>

      <div class="content">
        <p> Приве </p>
      </div>
    </div>
    
    <div id="number3" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Number 3
        <div>
          <button class="up"> /\ </button>
          <button class="down"> \/ </button>
        </div>
      </a>

      <div class="content">
        <p> こんにちは </p>
      </div>
    </div>
    
    <div id="number4" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Number 4
        <div>
          <button class="up"> /\ </button>
          <button class="down"> \/ </button>
        </div>
      </a>

      <div class="content">
        <p> 你好 </p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block script %}  <script src="{% static 'js/accordion.js' %}"></script> {% endblock %}

story_8/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/new-style.css' %}">
        {% block style %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
        {% block script %}{% endblock %}
    </body>
</html>

story_8/templates/story8.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Story8:Books
{% endblock title %}

{% block meta%}
<script src="{% static 'js/story8.js' %}"></script>
{% endblock meta%}

{% block content %}
<div class="container">
  <input class="form-control mb-4" id="tableSearch" type="text"
    placeholder="Type something to search list items">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Publisher</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody id="myTable">
      <tr>
        <td>Throne of Games</td>
        <td>Sometimes</td>
        <td>It's a book</td>
      </tr>
      <tr>
        <td>The Art of Debating by Shen Bapiro</td>
        <td>Daily Yes</td>
        <td>It's a book</td>
      </tr>
      <tr>
        <td>Solo</td>
        <td>Dooley</td>
        <td>It's a book</td>
      </tr>
      <tr>
        <td>Star Star: the Force</td>
        <td>Ravendale</td>
        <td>It's a book</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock content %}